### ISSUE TITLE
Import = Cannot find package

### ISSUE THREAD

**Issue by RatchetS2** [jesselpalmer/node-email-verifier#20]
After updating from 2.0 to 3.1, the package can't be imported anymore:
`import emailValidator from "node-email-verifier";`
Throw error: Cannot find package 'absolutePath\node_modules\node-email-verifier\dist\index.js'
Reverting to 2.0 fix the bug.

**Comment by jesselpalmer** [comment]
@RatchetS2 Thank you so much for letting me know! I am working on this now. A PR is on the way!

**Comment by jesselpalmer** [comment]
@RatchetS2 3.1.1 has been released with the fix! I added a bunch of tests that should help prevent this from happening in the future. Let me know if you have any issues. Thanks again!

**Comment by brentbaum** [comment]
Hi! Thanks for your work. I'm having a similar issue with 3.4.0. I've verified it's installed in the project. 

Background:

I'm using ES modules with Remix. NodeNext module resolution.

Error: Cannot find module 'email-validation/backend/node_modules/.pnpm/node-email-verifier@3.4.0/node_modules/node-email-verifier/dist/index.js' imported from email-validation/backend/node_modules/.pnpm/node-email-verifier@3.4.0/node_modules/node-email-verifier/dist/index.cjs
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:540:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:509:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:472:34)
    at defaultImportModuleDynamicallyForScript (node:internal/modules/esm/utils:227:31)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:249:12)
    at module.exports (email-validation/backend/node_modules/.pnpm/node-email-verifier@3.4.0/node_modules/node-email-verifier/dist/index.cjs:1:52)
